// <auto-generated />
using System;
using ContextLib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContextLib.Migrations
{
    [DbContext(typeof(WtaContext))]
    partial class WtaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Entities.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Handplay")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Entities.PlayerEntityResultEntity", b =>
                {
                    b.Property<int>("PlayerEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResultEntityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerEntityId", "ResultEntityId");

                    b.HasIndex("ResultEntityId");

                    b.ToTable("PlayerEntityResultEntity");
                });

            modelBuilder.Entity("Entities.ResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Entities.ResultEntityTournamentEntity", b =>
                {
                    b.Property<int>("ResultEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentEntityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResultEntityId", "TournamentEntityId");

                    b.HasIndex("TournamentEntityId");

                    b.ToTable("ResultEntityTournamentEntity");
                });

            modelBuilder.Entity("Entities.TournamentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("Entities.PlayerEntityResultEntity", b =>
                {
                    b.HasOne("Entities.PlayerEntity", null)
                        .WithMany()
                        .HasForeignKey("PlayerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.ResultEntity", null)
                        .WithMany()
                        .HasForeignKey("ResultEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.ResultEntityTournamentEntity", b =>
                {
                    b.HasOne("Entities.ResultEntity", null)
                        .WithMany()
                        .HasForeignKey("ResultEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.TournamentEntity", null)
                        .WithMany()
                        .HasForeignKey("TournamentEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
