kind: pipeline
type: docker
name: CI/CD

trigger:
  event:
    - push

steps:
  - name: build-and-publish
    image: mcr.microsoft.com/dotnet/sdk:9.0
    commands:
      # Change directory to the folder containing your solution.
      - cd WebApplicationJuaraujoda
      # Restore NuGet packages.
      - dotnet restore WebApplicationJuaraujoda.sln
      # Build the solution in Release mode without re-restoring.
      - dotnet build WebApplicationJuaraujoda.sln -c Release --no-restore
      # Publish the Web API project (adjust the path if necessary).
      - dotnet publish WebApplicationJuaraujoda/WebApplicationJuaraujoda/WtaApi.csproj -c Release --no-restore -o $CI_PROJECT_DIR/build/release
      # For debugging: list the published files.
      - echo "Published files:"
      - ls -R $CI_PROJECT_DIR/build/release

  - name: docker-build-and-push
    image: plugins/docker
    settings:
      # Path to your Dockerfile (adjust if your Dockerfile is located elsewhere).
      dockerfile: Dockerfile
      # Docker build context; here we use the root of the repository.
      context: .
      # URL of the Docker registry.
      registry: hub.codefirst.iut.uca.fr
      # Repository in the registry (ensure the repository name matches your account/repo).
      repo: hub.codefirst.iut.uca.fr/julien.araujo_da_silva/PM2_WebAPIAndEF_araujodasilva.julien
      # The following secrets must be defined in Drone (they contain your CodeFirst registry credentials).
      username:
        from_secret: SECRET_REGISTRY_USERNAME
      password:
        from_secret: SECRET_REGISTRY_PASSWORD
    depends_on:
      - build-and-publish
