kind: pipeline
type: docker
name: CI/CD

trigger:
  event:
    - push

steps:
  - name: build-and-publish
    image: mcr.microsoft.com/dotnet/sdk:9.0
    commands:
      - echo "Directory structure (root of repository):"
      - ls -R
      - dotnet restore WebApplicationJuaraujoda/WebApplicationJuaraujoda/WtaApi.csproj
      - dotnet build WebApplicationJuaraujoda/WebApplicationJuaraujoda/WtaApi.csproj -c Release --no-restore
      - dotnet publish WebApplicationJuaraujoda/WebApplicationJuaraujoda/WtaApi.csproj -c Release --no-restore -o ./build/release
      - echo "Published files:"
      - ls -R ./build/release

  - name: docker-build-and-push
    image: plugins/docker
    settings:
      dockerfile: WebApplicationJuaraujoda/Dockerfile
      context: .
      registry: hub.codefirst.iut.uca.fr
      repo: hub.codefirst.iut.uca.fr/julien.araujo_da_silva/pm2_webapiandef_araujodasilva.julien
      username:
        from_secret: SECRET_REGISTRY_USERNAME
      password:
        from_secret: SECRET_REGISTRY_PASSWORD
    depends_on:
      - build-and-publish

  - name: deploy-container
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
      IMAGENAME: hub.codefirst.iut.uca.fr/julien.araujo_da_silva/pm2_webapiandef_araujodasilva.julien:latest
      CONTAINERNAME: pm2-webapi
      COMMAND: create
      OVERWRITE: true
      # URL de base de l'API sur CodeFirst (AVEC HTTPS et le chemin complet)
      CODEFIRST_CLIENTDRONE_ENV_API_BASE_URL: https://julienaraujo_da_silva-pm2-webapi.apps.codefirst.iut.uca.fr/api/v1/Players
    depends_on:
      - docker-build-and-push