kind: pipeline
type: docker
name: CI/CD

trigger:
  event:
    - push

steps:
  - name: build-and-publish
    image: mcr.microsoft.com/dotnet/sdk:9.0
    commands:
      # Change directory to where the solution is located.
      - cd WebApplicationJuaraujoda
      # Print the directory tree to help debug the file structure.
      - echo "Directory structure (root of WebApplicationJuaraujoda):"
      - ls -R
      # Restore NuGet packages for the solution.
      - dotnet restore WebApplicationJuaraujoda.sln
      # Build the solution in Release mode without re-restoring.
      - dotnet build WebApplicationJuaraujoda.sln -c Release --no-restore
      # Publish the Web API project.
      # NOTE: If you get an error that the project file does not exist, check the output of ls -R
      # and adjust the path accordingly.
      - dotnet publish WebApplicationJuaraujoda/WebApplicationJuaraujoda/WtaApi.csproj -c Release --no-restore -o $CI_PROJECT_DIR/build/release
      # List the published files to confirm that publishing succeeded.
      - echo "Published files:"
      - ls -R $CI_PROJECT_DIR/build/release

  - name: docker-build-and-push
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      context: .
      registry: hub.codefirst.iut.uca.fr
      repo: hub.codefirst.iut.uca.fr/julien.araujo_da_silva/PM2_WebAPIAndEF_araujodasilva.julien
      username:
        from_secret: SECRET_REGISTRY_USERNAME
      password:
        from_secret: SECRET_REGISTRY_PASSWORD
    depends_on:
      - build-and-publish
