kind: pipeline
type: docker
name: CI

trigger:
  event:
    - push

steps:
  - name: restore-build-publish
    image: mcr.microsoft.com/dotnet/sdk:9.0
    commands:
      - cd WebApplicationJuaraujoda
      - dotnet restore WebApplicationJuaraujoda.sln
      - dotnet build WebApplicationJuaraujoda.sln -c Release --no-restore
      # Note: Adjust the project file path to where your WtaApi.csproj actually is.
      - dotnet publish WebApplicationJuaraujoda/WtaApi.csproj -c Release --no-restore -o $CI_PROJECT_DIR/build/release
