// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StubbedContextLib;

#nullable disable

namespace StubbedContextLib.Migrations
{
    [DbContext(typeof(StubbedContext))]
    [Migration("20250213103905_myFirstMigration")]
    partial class myFirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Entities.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Handplay")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 42,
                            BirthDate = new DateTime(1998, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Aryna",
                            Handplay = 3,
                            Height = 1.82f,
                            LastName = "Sabalenka",
                            Nationality = "Belarus"
                        },
                        new
                        {
                            Id = 43,
                            BirthDate = new DateTime(2001, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Iga",
                            Handplay = 3,
                            Height = 1.76f,
                            LastName = "Swiatek",
                            Nationality = "Poland"
                        },
                        new
                        {
                            Id = 44,
                            BirthDate = new DateTime(2004, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Coco",
                            Handplay = 3,
                            Height = 1.75f,
                            LastName = "Gauff",
                            Nationality = "USA"
                        },
                        new
                        {
                            Id = 45,
                            BirthDate = new DateTime(1996, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jasmine",
                            Handplay = 3,
                            Height = 1.63f,
                            LastName = "Paolini",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = 46,
                            BirthDate = new DateTime(2002, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Qinwen",
                            Handplay = 3,
                            Height = 1.78f,
                            LastName = "Zheng",
                            Nationality = "China"
                        },
                        new
                        {
                            Id = 47,
                            BirthDate = new DateTime(1999, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Elena",
                            Handplay = 3,
                            Height = 1.84f,
                            LastName = "Rybakina",
                            Nationality = "Kazakhstan"
                        },
                        new
                        {
                            Id = 48,
                            BirthDate = new DateTime(1994, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jessica",
                            Handplay = 3,
                            Height = 1.7f,
                            LastName = "Pegula",
                            Nationality = "USA"
                        },
                        new
                        {
                            Id = 49,
                            BirthDate = new DateTime(2001, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emma",
                            Handplay = 3,
                            Height = 1.7f,
                            LastName = "Navarro",
                            Nationality = "USA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
